# SPDX-FileCopyrightText: 2026 Arcangelo Massari <info@arcangelomassari.com>
#
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Build Windows

on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Setup Flutter
        uses: subosito/flutter-action@1a449444c387b1966244ae4d4f8c696479add0b2 # v2.23.0
        with:
          channel: stable
          cache: true

      - name: Get dependencies
        run: flutter pub get

      - name: Build MSIX
        run: dart run msix:create --store

      - name: Upload MSIX artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: windows-msix
          path: build/windows/x64/runner/Release/*.msix

      - name: Upload metadata artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          name: windows-metadata
          path: windows/metadata.json
